title: Yudi Ko
subtitle: avid doodler. engineer. adventurist. climber. musician
description: Intentional Living | Self-Awareness

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Gallery
      url: /gallery
    - text: Music
      url: /music
    - text: Podcast
      url: /podcast
    # - text: Shop
     # url : /shop
    - text: Contact Me
      url : /contact


# Edit these details

author_logo: profile.png
author: Yudi
author_bio: Hi! I'm Yudi. I'm a Mechanical Engineer by training, currently working for Siemens Government Technologies and pursuing my MBA. In my free time, I work on my various projects, ranging from producing music to rock climbing. Check out more of my projects in my website! Feel free to contact me if you would like to collaborate or just want to have interesting dialogue :) 
author_email: "yudiko@vt.edu"
author_location: Salt Lake City, UT
author_website_url: "https://yudiko.github.io/"
typewrite-text: I'm a(n) avid doodler, engineer, adventurist, climber, and musician. 

author_work_experiences:
            - company_name: Siemens Government Technologies
              company_logo: siemens.png
              company_url: https://www.siemensgovt.com/
              designation: Implementation Consultant
              description: Implement Siemens Software
              visibility: true
            - company_name: GE Aviation
              company_logo: ge.png
              company_url: https://www.geaviation.com/
              designation: Data Engineer
              description: Led a Data Visualization Project
              visibility: true
            - company_name: Rolls-Royce
              company_logo: rollsroyce.png
              company_url: https://www.rolls-royce.com/
              designation: Business Improvement Intern
              description: Implemented a Tracking System; Led Improvement Projects
              visibility: true
            - company_name: GE Aviation
              company_logo: ge.png
              company_url: https://www.geaviation.com/
              designation: Mech. Engineering Co-op
              description: Worked on Mechanical System Projects
              visibility: true

author_education_details:
              - college_logo: vt.png
                college_name: Virginia Tech
                college_url: https://vt.edu/
                college_degree: Mechanical Engineer (2014-2018)
                description: B.S. Mechanical Engineering
                visibility: true
              - college_logo: uou.png
                college_name: University of Utah
                college_url: https://www.utah.edu/
                college_degree: MBA (2020-2020)
                description: Master of Business Administration
                visibility: true

doodles_details:
              - drawing: profile.png
                drawing1: devon.png
                drawing2: cam.png
                drawing3: hamza.png
                visibility: true
              - drawing: drawing1.jpg
                drawing1: drawing2.jpg
                drawing2: drawing3.jpg
                drawing3: drawing4.jpg
                visibility: true
              - drawing: drawing5.jpg
                drawing1: drawing6.jpg
                drawing2: drawing7.jpg
                drawing3: drawing8.jpg 
                visibility: true
              - drawing: drawing9.jpg
                drawing1: drawing10.jpg
                drawing2: drawing11.jpg
                drawing3: drawing12.jpg 
                visibility: true


# social links
linkedin_username: yudi-ko
instagram_username: yudiofficialmusic
# YouTube_username: UCBngJ1efJfFtKdmBZWKo-kg
# Spotify_username: 6YZyPyJyWzaGBRsRNZ0ZHP


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: yudiko@vt.edu

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_doodles_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
